baseurl = "https://www.apparmor.net/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "AppArmor"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "aa-beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  subtitle = "Linux kernel security module"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 02, 2006"
  commit = false
  rss = true
  comments = true

[Author]
  gitlab = "apparmor"
  launchpad = "apparmor"
  wikipedia = "apparmor"

[[menu.main]]
    name = "News"
    url = "/news/"
    weight = 1

[[menu.main]]
    name = "Wiki"
    url = "https://gitlab.com/apparmor/apparmor/wikis/home"
    weight = 3

[[menu.main]]
    name = "Documentation"
    url = "https://gitlab.com/apparmor/apparmor/wikis/Documentation"
    weight = 3

[[menu.main]]
    name = "Development"
    url = "https://gitlab.com/apparmor/"
    weight = 3

[[menu.main]]
    name = "Twitter"
    pre = "<i class='fa fa-twitter' aria-hidden='true'></i>"
    url = "https://twitter.com/ApparmorProject"
    weight = 4
